#ifndef DISTRHO_PLUGIN_INFO_H_INCLUDED
#define DISTRHO_PLUGIN_INFO_H_INCLUDED

#define DISTRHO_PLUGIN_NAME  "Super Saw"
#define DISTRHO_PLUGIN_URI   "https://github.com/cranixx/Super_Saw_DPF"
#define DISTRHO_PLUGIN_NUM_INPUTS 1
#define DISTRHO_PLUGIN_NUM_OUTPUTS 1
#define DISTRHO_PLUGIN_IS_SYNTH   1

#endif // DISTRHO_PLUGIN_INFO_H_INCLUDED

