#ifndef DISTRHO_PLUGIN_INFO_H_INCLUDED
#define DISTRHO_PLUGIN_INFO_H_INCLUDED

#define DISTRHO_PLUGIN_NAME  "Super Saw"
#define DISTRHO_PLUGIN_URI   "http://example.org/Super_Saw"
#define DISTRHO_PLUGIN_NUM_INPUTS 0
#define DISTRHO_PLUGIN_NUM_OUTPUTS 1

#endif // DISTRHO_PLUGIN_INFO_H_INCLUDED

